"use client";
import { useState } from "react";

export function EmailEditor({ title, note, subject, body, html, hidden }: { title:string; note:string; subject:string; body:string; html:string; hidden:Record<string,string> }) {
  const [subjectValue,setSubject]=useState(subject);const [bodyValue,setBody]=useState(body);const [copied,setCopied]=useState("");
  async function copySubject(){await navigator.clipboard.writeText(subjectValue);setCopied("subject");setTimeout(()=>setCopied(""),1400);}
  async function copyBody(){const holder=document.getElementById("email-preview");const plain=holder?.innerText||bodyValue;try{await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([plain],{type:"text/plain"})})]);}catch{await navigator.clipboard.writeText(plain);}setCopied("body");setTimeout(()=>setCopied(""),1800);}
  return <form className="card emailEditor" action="/api/email-drafts" method="post">{Object.entries(hidden).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<div className="notice">{note}</div><div className="subjectRow"><label><span>邮件主题</span><input name="subject" value={subjectValue} onChange={(event)=>setSubject(event.target.value)} required/></label><button className="secondary" type="button" onClick={copySubject}>{copied==="subject"?"已复制":"复制主题"}</button></div><div className="sectionTitle emailTitle"><h2>{title}</h2><button type="button" onClick={copyBody}>{copied==="body"?"已复制，可粘贴到 Outlook":"复制格式化正文"}</button></div><div id="email-preview" className="emailPreview" dangerouslySetInnerHTML={{__html:html}}/><details className="plainDraft"><summary>查看或修改纯文本备用版本</summary><label><span>纯文本正文</span><textarea name="body" rows={18} value={bodyValue} onChange={(event)=>setBody(event.target.value)} required/></label></details><div className="formActions"><a href={`/group?vessel=${encodeURIComponent(hidden.vessel)}`}>取消</a><button className="secondary" type="submit">保存邮件草稿</button></div></form>;
}
