import { redirect } from "next/navigation";
import { PaymentProofUpload } from "../../components/PaymentProofUpload";
import { ReleaseToggle } from "../../components/ReleaseToggle";
import { all, first } from "../../lib/db";
import { ownerGroups } from "../../lib/grouping";
import type { EmailDraftRow, FreeDayRow, InvoiceRow, PaymentProofRow, ReleaseRow } from "../../lib/types";
import { totals } from "../../lib/utils";

export const dynamic = "force-dynamic";

export default async function GroupPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const query=await searchParams; const vessel=typeof query.vessel==="string"?query.vessel.trim():""; if(!vessel) redirect("/");
  const [invoices,plans,releases,proofs,drafts,archive]=await Promise.all([
    all<InvoiceRow>("SELECT * FROM invoices WHERE vessel_name=? ORDER BY owner_name,owner_email,invoice_no,id",[vessel]),
    all<FreeDayRow>("SELECT * FROM container_free_days WHERE vessel_name=?",[vessel]), all<ReleaseRow>("SELECT * FROM container_releases WHERE vessel_name=?",[vessel]), all<PaymentProofRow>("SELECT * FROM payment_proofs WHERE vessel_name=? ORDER BY created_at DESC",[vessel]), all<EmailDraftRow>("SELECT * FROM email_drafts WHERE vessel_name=?",[vessel]), first<{vessel_name:string}>("SELECT vessel_name FROM vessel_archives WHERE vessel_name=?",[vessel])]);
  if(!invoices.length)return <main><div className="card empty">没有找到这条船。<br/><a href="/">返回首页</a></div></main>;
  const groups=ownerGroups(invoices,plans,releases,proofs,drafts); const eta=invoices.find((invoice)=>invoice.eta)?.eta||""; const grandTotals=totals(invoices); const today=new Date().toISOString().slice(0,10);
  return <main>
    <div className="pageHeading"><div><p className="eyebrow">STEP 3 · VESSEL SUMMARY</p><h1>{vessel}</h1><p>{invoices.length} 份账单 · {groups.length} 个船东</p></div><div className="actions"><a className="button secondary" href={`/api/export?vessel=${encodeURIComponent(vessel)}`}>导出本船 Excel</a>{archive?<form action="/api/group/restore" method="post"><input type="hidden" name="vessel" value={vessel}/><button type="submit">恢复到当前船舶</button></form>:<form action="/api/group/archive" method="post"><input type="hidden" name="vessel" value={vessel}/><button className="finish" type="submit">结束本船</button></form>}<a href={archive?"/history":"/"}>返回{archive?"历史记录":"当前船舶"}</a></div></div>
    {query.saved&&<div className="notice">修改已经保存到在线数据库。</div>}
    <section className="card summaryBar"><form className="etaForm" action="/api/group/eta" method="post"><input type="hidden" name="vessel" value={vessel}/><label><span>本船统一 ETA</span><input type="date" name="eta" defaultValue={eta}/></label><button className="secondary" type="submit">更新 ETA</button></form><div><span className="muted">整船账单合计</span>{grandTotals.map((total)=><strong className="grandTotal" key={total.currency}>{total.currency} {total.amount}</strong>)}</div></section>
    <div className="outsideTitle"><div><p className="eyebrow">OWNER SUMMARY</p><h2>按船东汇总</h2></div><span>每个船东可独立管理账单、延期、付款截图和 Release</span></div>
    <div className="ownerGrid">{groups.map((owner)=><details className="card ownerCard" key={`${owner.ownerName}-${owner.ownerEmail}`}>
      <summary className="ownerSummary"><span><strong>{owner.ownerName||"待补充船东"}</strong><small>{owner.ownerEmail||"待补充邮箱"} · {owner.containers.length} 个集装箱 · {owner.invoices.length} 份账单 · {owner.totals.map((total)=>`${total.currency} ${total.amount}`).join(" / ")||"暂无金额"} · Release {owner.releasedCount}/{owner.containers.length}</small></span><span className="summaryBadges">{owner.extensionCount>0&&<em className="badge warning">需延长 {owner.extensionCount} 个柜</em>}{owner.extensionInvoiceCount>0&&<em className="badge success">延期账单 {owner.extensionInvoiceCount} 份</em>}<em className="badge">{owner.proofs.length?`付款截图 ${owner.proofs.length} 张`:"未上传付款截图"}</em><em className="toggleLabel"/></span></summary>
      <div className="ownerContent"><dl className="ownerStats"><div><dt>账单</dt><dd>{owner.invoices.length}</dd></div><div><dt>集装箱</dt><dd>{owner.containers.length}</dd></div><div><dt>Release</dt><dd>{owner.releasedCount}/{owner.containers.length}</dd></div><div><dt>合计</dt><dd>{owner.totals.map((total)=><span key={total.currency}>{total.currency} {total.amount}</span>)}</dd></div></dl>
      <section className="workflowBox"><div className="sectionTitle"><div><h3>Last Free Day / 提柜计划</h3><small>可一键设置本船东所有集装箱，也可在下表逐个修改；系统自动计算延期天数。</small></div><span>{owner.extensionCount?`${owner.extensionCount} 个柜需要延期`:"目前无柜需要延期"}</span></div><form className="bulkForm" action="/api/group/free-days" method="post"><input type="hidden" name="vessel" value={vessel}/><input type="hidden" name="owner" value={owner.ownerName}/><input type="hidden" name="scope" value="owner"/><label><span>统一 Last Free Day</span><input type="date" name="last_free_day" defaultValue={owner.bulkLastFreeDay}/></label><label><span>统一计划提柜日期</span><input type="date" name="pickup_date" defaultValue={owner.bulkPickupDate}/></label><button className="secondary" type="submit">一键应用到全部集装箱</button></form></section>
      <p className="tableHelp">点击集装箱号或账单号可回到完整校正页面。</p><div className="tableWrap"><table className="containerTable"><thead><tr><th>集装箱号</th><th>B/L No.</th><th>尺寸</th><th>账单</th><th>该箱总金额</th><th>Last Free Day</th><th>计划提柜</th><th>延期</th><th>Release</th></tr></thead><tbody>{owner.containers.map((container)=>{const formId=`free-${container.invoices[0].id}`;return <tr key={container.containerNo}><td><a className="vessel" href={`/invoice/${container.invoices[0].id}`}>{container.containerNo}</a></td><td>{container.blNos.join(", ")||"—"}</td><td>{container.sizes.join(", ")||"—"}</td><td><span className={`badge ${container.invoices.length>1?"warning":""}`}>{container.invoices.length} 份账单</span><small className="invoiceLinks">{container.invoices.map((invoice)=><span key={invoice.id}><a href={`/invoice/${invoice.id}`}>{invoice.invoice_no||"未填写账单号"}</a>{invoice.invoice_category==="last_free_day_extension"&&<em className="badge extension">延期</em>}</span>)}</small></td><td><strong>{container.totals.map((total)=><span key={total.currency}>{total.currency} {total.amount}</span>)}</strong></td><td><input className="compactDate" type="date" name="last_free_day" defaultValue={container.lastFreeDay} form={formId}/></td><td><input className="compactDate" type="date" name="pickup_date" defaultValue={container.pickupDate} form={formId}/></td><td>{container.extensionDays>0?<span className="badge warning">延长 {container.extensionDays} 天</span>:container.lastFreeDay&&container.pickupDate?<span className="badge success">无需延长</span>:<span className="badge">待设置</span>}<form id={formId} action="/api/group/free-days" method="post"><input type="hidden" name="vessel" value={vessel}/><input type="hidden" name="owner" value={owner.ownerName}/><input type="hidden" name="scope" value="container"/><input type="hidden" name="container" value={container.containerNo}/><button className="linkButton" type="submit">保存</button></form></td><td><ReleaseToggle vessel={vessel} owner={owner.ownerName} container={container.containerNo} initial={container.released}/></td></tr>})}</tbody></table></div>
      <div className="extensionActions">{owner.extensionCount?<a className="button" href={`/email/free-day-extension?vessel=${encodeURIComponent(vessel)}&owner=${encodeURIComponent(owner.ownerName)}&email=${encodeURIComponent(owner.ownerEmail)}`}>生成/编辑延期邮件（{owner.extensionCount} 个柜）</a>:<span className="muted">设置日期后，系统会在这里开放延期邮件。</span>}</div>
      <section className="workflowBox"><div className="sectionTitle"><div><h3>导入延长免租期账单</h3><small>船东返回账单后在这里导入，再次核对后自动计入付款合计。</small></div><span>{owner.extensionInvoiceCount?`已导入 ${owner.extensionInvoiceCount} 份`:"尚未导入"}</span></div><form className="extensionUpload" action="/api/extension-invoices" method="post" encType="multipart/form-data"><input type="hidden" name="vessel" value={vessel}/><input type="hidden" name="owner" value={owner.ownerName}/><input type="hidden" name="email" value={owner.ownerEmail}/><label><span>对应集装箱（可选）</span><select name="container_hint"><option value="">由 PDF 自动识别</option>{owner.containers.map((container)=><option key={container.containerNo}>{container.containerNo}</option>)}</select></label><label><span>延期账单 PDF（可多选）</span><input type="file" name="extension_pdfs" accept="application/pdf,.pdf" multiple required/></label><button className="secondary" type="submit">导入并重新审核</button></form></section>
      <section className="workflowBox"><div className="sectionTitle"><div><h3>付款截图</h3><small>可选凭证；支持选择或直接从剪贴板粘贴一张或多张图片。</small></div><span>{owner.proofs.length?`已保存 ${owner.proofs.length} 张`:"尚未上传"}</span></div>{owner.proofs.length>0&&<div className="proofGrid">{owner.proofs.map((proof)=><article className="proofItem" key={proof.id}><a target="_blank" href={`/payment-proof/${proof.id}/file`}><img src={`/payment-proof/${proof.id}/file`} alt={`付款截图 ${proof.source_filename}`}/></a><div><strong>{proof.payment_date||"未填写付款日期"}</strong><small>{proof.source_filename}</small><form action={`/api/payment-proofs/${proof.id}/delete`} method="post"><button className="linkDanger" type="submit">移除</button></form></div></article>)}</div>}<PaymentProofUpload vessel={vessel} owner={owner.ownerName} defaultDate={owner.proofs[0]?.payment_date||today}/></section>
      <div className="workflowActions">{owner.isCosco&&<a className="button secondary" href={`/email/cosco-request?vessel=${encodeURIComponent(vessel)}&owner=${encodeURIComponent(owner.ownerName)}&email=${encodeURIComponent(owner.ownerEmail)}`}>1. 生成/编辑 COSCO 索账邮件</a>}<a className="button" href={`/email/payment-release?vessel=${encodeURIComponent(vessel)}&owner=${encodeURIComponent(owner.ownerName)}&email=${encodeURIComponent(owner.ownerEmail)}`}>{owner.isCosco?"2. ":""}生成付款后 Release 邮件</a></div>
      </div></details>)}</div>
  </main>;
}
