import { extractText, getDocumentProxy } from "unpdf";
import { all, bindings, first, nowIso, run } from "../../../lib/db";
import { extractFields } from "../../../lib/extract";
import { applyLearnedCorrections } from "../../../lib/learning";
import type { InvoiceRow, LearningExampleRow } from "../../../lib/types";
import { normalizeInvoiceNo, safeFilename, splitContainers } from "../../../lib/utils";
import { validateExtractedFields } from "../../../lib/validation";

export async function POST(request:Request){
  const form=await request.formData();const vessel=String(form.get("vessel")||"").trim();const owner=String(form.get("owner")||"").trim();const email=String(form.get("email")||"").trim();const hint=String(form.get("container_hint")||"").trim();const files=form.getAll("extension_pdfs").filter((item):item is File=>item instanceof File&&item.size>0);
  const related=await all<InvoiceRow>("SELECT * FROM invoices WHERE vessel_name=? AND owner_name=? ORDER BY id",[vessel,owner]);if(!related.length)return Response.redirect(new URL("/",request.url),303);const containers=Array.from(new Set(related.flatMap((invoice)=>splitContainers(invoice.container_no))));if(hint&&!containers.includes(hint))return new Response("Invalid container",{status:400});const eta=related.find((invoice)=>invoice.eta)?.eta||"";const port=related.find((invoice)=>invoice.port_of_discharge)?.port_of_discharge||"";const created:number[]=[];const duplicates:number[]=[];const learningExamples=await all<LearningExampleRow>("SELECT * FROM learning_examples ORDER BY updated_at DESC LIMIT 80");
  for(const file of files){if(!file.name.toLowerCase().endsWith(".pdf")&&file.type!=="application/pdf")continue;const bytes=new Uint8Array(await file.arrayBuffer());let raw="",warning="";try{const pdf=await getDocumentProxy(bytes);const result=await extractText(pdf,{mergePages:true});raw=result.text;if(!raw.trim())warning="PDF 没有可提取文字，请手工填写。";}catch{warning="PDF 文字提取失败，请手工核对。";}const learned=applyLearnedCorrections(raw,extractFields(raw),learningExamples);const fields=learned.fields;fields.vessel_name=vessel;fields.owner_name=owner;fields.owner_email=email;fields.eta=fields.eta||eta;fields.port_of_discharge=fields.port_of_discharge||port;if(hint)fields.container_no=hint;const validation=validateExtractedFields(fields);warning=[warning,validation.length?`请重点核对：${validation.join("；")}。`:""].filter(Boolean).join("\n");const keyNo=normalizeInvoiceNo(fields.invoice_no);if(keyNo){const duplicate=await first<Pick<InvoiceRow,"id">>("SELECT id FROM invoices WHERE invoice_no_key=?",[keyNo]);if(duplicate){duplicates.push(duplicate.id);continue;}}
    const fileKey=`invoices/${crypto.randomUUID()}.pdf`;await bindings().FILES.put(fileKey,bytes,{httpMetadata:{contentType:"application/pdf"},customMetadata:{originalName:safeFilename(file.name)}});const now=nowIso();const inserted=await run(`INSERT INTO invoices (source_filename,file_key,raw_text,extraction_warning,learning_note,invoice_category,vessel_name,voyage_no,eta,invoice_no,invoice_no_key,invoice_date,owner_name,owner_email,port_of_discharge,container_no,container_size,bl_no,charge_details,amount,currency,status,created_at,updated_at) VALUES (?,?,?,?,?,'last_free_day_extension',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'待校正',?,?)`,[safeFilename(file.name),fileKey,raw,warning,learned.note,fields.vessel_name,fields.voyage_no,fields.eta,fields.invoice_no,keyNo,fields.invoice_date,fields.owner_name,fields.owner_email,fields.port_of_discharge,fields.container_no,fields.container_size,fields.bl_no,fields.charge_details,fields.amount,fields.currency,now,now]);created.push(Number(inserted.meta.last_row_id));
  }
  if(created.length)return Response.redirect(new URL(`/invoice/${created[0]}?uploaded=${created.length}`,request.url),303);if(duplicates.length)return Response.redirect(new URL(`/invoice/${duplicates[0]}?duplicate=1`,request.url),303);return Response.redirect(new URL(`/group?vessel=${encodeURIComponent(vessel)}`,request.url),303);
}
