import type { InvoiceRow } from "./types";
import { amountNumber, formatDate, splitContainers } from "./utils";

const esc=(value:string)=>value.replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!);
const shell=(content:string)=>`<div style="font-family:Arial,sans-serif;font-size:14px;line-height:1.55;color:#1f1f1f">${content}</div>`;

export function coscoRequestEmail(vessel:string,invoices:InvoiceRow[]){const rows=invoices.flatMap((invoice)=>(splitContainers(invoice.container_no).length?splitContainers(invoice.container_no):["-"]).map((container)=>({vessel,eta:formatDate(invoice.eta),bl:invoice.bl_no||"-",container})));const subject=`Release - ${vessel} // Cargo Move Ltd`;const lines=rows.map((row)=>`${row.vessel}\t${row.eta}\t${row.bl}\t${row.container}`).join("\n");const body=`Hello COSCO team,\n\nCould you please help forward us the THC LOLO invoice for below containers? Thank you.\n\nVessel\tETA\tBL Reference\tContainer\n${lines}\n\nThank you.`;const table=`<table style="border-collapse:collapse;margin:18px 0"><thead><tr>${["Vessel","ETA","BL Reference","Container"].map((h)=>`<th style="border:1px solid #222;background:#fff3a7;padding:7px 14px">${h}</th>`).join("")}</tr></thead><tbody>${rows.map((row)=>`<tr>${[row.vessel,row.eta,row.bl,row.container].map((v)=>`<td style="border:1px solid #222;padding:4px 8px">${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;return{subject,body,html:shell(`<p>Hello COSCO team,</p><p>Could you please help forward us the THC LOLO invoice for below containers? Thank you.</p>${table}<p>Thank you.</p>`)};}

export function freeDayEmail(rows:{containerNo:string;pickupDate:string}[],vessel:string){const subject=`Last Free Day Extension - ${vessel} // Cargo Move Ltd`;const items=rows.map((row)=>`${row.containerNo} extend to ${formatDate(row.pickupDate)}`).join("\n");const body=`Hi team,\n\nCould you please also help extend the below container${rows.length>1?"s":""} and forward us the invoice? Thank you.\n\n${items}\n\nThank you.`;const html=shell(`<p>Hi team,</p><p>Could you please also help extend the below container${rows.length>1?"s":""} and forward us the invoice? Thank you.</p><div style="margin:18px 0">${rows.map((row)=>`<div style="margin:7px 0"><strong>${esc(row.containerNo)}</strong> extend to <strong>${esc(formatDate(row.pickupDate))}</strong></div>`).join("")}</div><p>Thank you.</p>`);return{subject,body,html};}

export function paymentReleaseEmail(vessel:string,invoices:InvoiceRow[],paymentDate:string,isCosco:boolean){const grouped=new Map<string,number>();for(const invoice of invoices)grouped.set(invoice.currency,(grouped.get(invoice.currency)||0)+amountNumber(invoice.amount));const totalLabel=Array.from(grouped,([currency,value])=>`${value.toFixed(2)}${currency}`).join(" / ");const subject=`Re: Release - ${vessel} // Remittance ${totalLabel} Cargo Move Ltd`;const rows=invoices.flatMap((invoice)=>(splitContainers(invoice.container_no).length?splitContainers(invoice.container_no):["-"]).map((container)=>({paymentDate:formatDate(paymentDate),invoiceValue:`${invoice.currency} ${amountNumber(invoice.amount).toFixed(2)}`,invoiceNo:invoice.invoice_no||"-",invoiceDate:formatDate(invoice.invoice_date),vessel,eta:formatDate(invoice.eta),bl:invoice.bl_no||"-",container})));const header=isCosco?"Good day COSCO team,":"Hi team,";const intro=isCosco?"Could you please help allocate this payment and release to our badge GKM? Thank you.":"Please find the payment details below. Thank you.";const columns=["Payment Date","Invoice Value","Invoice Number","Invoice Date","Vessel","ETA","BL Reference","Container"] as const;const lines=rows.map((row)=>[row.paymentDate,row.invoiceValue,row.invoiceNo,row.invoiceDate,row.vessel,row.eta,row.bl,row.container].join("\t")).join("\n");const body=`${header}\n\n${intro}\n\nPlease find the payment details:\n${columns.join("\t")}\n${lines}\n\nThank you.`;const table=`<table style="border-collapse:collapse;margin:18px 0"><thead><tr>${columns.map((h)=>`<th style="border:1px solid #222;background:#fff3a7;padding:7px 10px">${h}</th>`).join("")}</tr></thead><tbody>${rows.map((row)=>`<tr>${[row.paymentDate,row.invoiceValue,row.invoiceNo,row.invoiceDate,row.vessel,row.eta,row.bl,row.container].map((v)=>`<td style="border:1px solid #222;background:#ffcdd2;padding:5px 8px">${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;return{subject,body,html:shell(`<p>${esc(header)}</p><p>${esc(intro)}</p><p>Please find the payment details:</p>${table}<p>Thank you.</p>`)};}
